asset = "0x4c58A838E6FccE71237FB07ab078B49474086496"
assetPriceUSD = "10"
depositorAssetFinalBalance = "400"
depositorAssetInitialBalance = "450"
depositorWIronFinalBalance = "500"
depositorWIronInitialBalance = "0"
vaultAssetFinalBalance = "300"
vaultAssetInitialBalance = "250"
vaultWIronFinalBalance = "1000"
vaultWIronInitialBalance = "1500"
wIronPriceUSD = "1"
